# Generated by Django 4.1.3 on 2022-11-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0002_herosection_mailing_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='photo',
            field=models.ImageField(upload_to='img/hero'),
        ),
    ]
