# Generated by Django 4.1.3 on 2022-11-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0003_alter_herosection_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='photo',
            field=models.ImageField(height_field=801, upload_to='img/hero', width_field=1920),
        ),
    ]
