# Generated by Django 4.1.3 on 2022-11-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0005_alter_herosection_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_title', models.CharField(blank=True, max_length=50, null=True)),
                ('first_photo', models.ImageField(blank=True, null=True, upload_to='img/banner')),
                ('second_title', models.CharField(blank=True, max_length=50, null=True)),
                ('second_photo', models.ImageField(blank=True, null=True, upload_to='img/banner')),
                ('third_title', models.CharField(blank=True, max_length=50, null=True)),
                ('third_photo', models.ImageField(blank=True, null=True, upload_to='img/banner')),
            ],
            options={
                'verbose_name': 'Banner Section',
                'verbose_name_plural': 'Banner Sections',
            },
        ),
        migrations.AlterModelOptions(
            name='herosection',
            options={'verbose_name': 'Hero Section', 'verbose_name_plural': 'Hero Sections'},
        ),
        migrations.AlterField(
            model_name='mailing',
            name='photo',
            field=models.ImageField(upload_to='img/mailing'),
        ),
    ]
