# Generated by Django 4.1.3 on 2022-11-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0006_bannersection_alter_herosection_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='img/latest')),
                ('title', models.CharField(max_length=100, verbose_name='Название блога')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
        migrations.CreateModel(
            name='NewSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_sale', models.CharField(blank=True, max_length=100, null=True, verbose_name='Прошлая скидка')),
                ('now_sale', models.CharField(blank=True, max_length=100, null=True, verbose_name='Новая скидка')),
                ('future_sale', models.CharField(blank=True, max_length=100, null=True, verbose_name='Скоро')),
                ('picture', models.ImageField(upload_to='img/sale')),
                ('price', models.CharField(blank=True, max_length=20, null=True, verbose_name='Цена включая скидку')),
                ('title', models.CharField(default='DEAL OF THE WEEK', max_length=50)),
                ('name', models.CharField(max_length=100, verbose_name='Название акции')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
            },
        ),
        migrations.AlterField(
            model_name='bannersection',
            name='first_title',
            field=models.CharField(blank=True, help_text='Test help text', max_length=50, null=True, verbose_name='Название первого баннера'),
        ),
        migrations.AlterField(
            model_name='bannersection',
            name='second_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название второго баннера'),
        ),
        migrations.AlterField(
            model_name='bannersection',
            name='third_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название третьего баннера'),
        ),
    ]
