# Generated by Django 4.1.3 on 2022-11-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0008_latestblog_author_latestblog_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailForMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
